# yaml-language-server: $schema=https://json.schemastore.org/pull-request-labeler-5.json

server:
  - changed-files:
      - any-glob-to-any-file:
          - apps/server/**

client:
  - changed-files:
      - any-glob-to-any-file:
          - packages/client/**
config:
  - changed-files:
      - any-glob-to-any-file:
          - packages/config/**
