name: GitHub Pages

on:
  push:
    branches: main

jobs:
  build_pages:
    runs-on: ubuntu-latest

    if: github.actor != 'nektos/act'

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: actions/setup-node@v5
        with:
          node-version: latest
          cache: pnpm

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy_pages:
    needs: build_pages

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
