name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_pages:
    permissions:
      contents: read

    if: github.actor != 'nektos/act'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: actions/setup-node@v5
        with:
          node-version: latest
          cache: pnpm

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run docs

      - run: |
          pnpm run test:coverage
          cp --force --recursive coverage docs/coverage

      - run: |
          pnpm dlx turbo run test:coverage
          cp --force --recursive apps/server/coverage docs/coverage-server
          cp --force --recursive packages/client/coverage docs/coverage-client

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs

  deploy_pages:
    permissions:
      pages: write
      id-token: write

    needs: build_pages

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
