name: Labeler

on:
  pull_request:
    branches:
      - main

jobs:
  labeler:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v6
        with:
          configuration-path: .github/labeler-sync.yaml
          sync-labels: true

      - uses: actions/labeler@v6
        with:
          configuration-path: .github/labeler.yaml
          sync-labels: false
