name: Lint & Fix

on:
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
      - run: corepack use pnpm@latest
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run lint:fix
      - run: pnpm install --fix-lockfile

      - uses: qoomon/actions--create-commit@v1
        id: commit
        with:
          message: |
            🎨 pnpm run lint:fix

            [dependabot skip]
          skip-empty: true

      - if: steps.commit.outputs.commit != null
        run: git push
