name: Node.js CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run test
        env:
          TOKEN: ${{ secrets.SERVER_TOKEN }}
